### ISSUE TITLE
IEMobile 11 Update User Agent Changes

### ISSUE THREAD

**Issue by kiding** [gabceb/jquery-browser-plugin#33]
[Microsoft announced](http://blogs.msdn.com/b/ie/archive/2014/07/31/the-mobile-web-should-just-work-for-everyone.aspx) that Internet Explorer 11 in the upcoming Windows Phone 8.1 Update will change the user agent (again) and it looks somewhat like this.

> Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 920) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537 ([Ref](https://twitter.com/rubik_orange/status/496287745874989056))

> Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; 909) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537 ([Ref](https://twitter.com/carlcamera/status/496293377810239488))

Jesus.

The update would take months to get to the consumers, so it is _kind of_ subject to change, hopefully, but unlikely.

[Here](http://www.reddit.com/r/windowsphone/comments/2cky49/windows_phone_81_update_1_released/cjghxf2) is a reddit thread if you're interested.

**Comment by le717** [comment]
It looks like the UA changes have made it to users:

https://twitter.com/clindhartsen/status/554399930526101504

We'll have to fix this soon. If there were priority labels, I'd raise the priority. :P

**Comment by MoonYard** [comment]
Shouldn't it fixed now?

**Comment by le717** [comment]
Totally forgot this issue was filed before. Fixed in #70, closing.

**Comment by gabceb** [comment]
Thanks @le717 @MoonYard  (+ everyone else)
