### ISSUE TITLE
Wrong version number on Safari

### ISSUE THREAD

**Issue by lehni** [gabceb/jquery-browser-plugin#35]
According to http://api.jquery.com/jquery.browser/#jQuery-browser-version2, `jQuery.browser.version` is supposed to be the browser's rendering engine version number, not the version number of the browser itself.

But on Safari 8 I get `8.0`, while http://code.jquery.com/jquery-migrate-1.2.1.js gives the correct `600.1.22`

**Comment by mightyiam** [comment]
@lehni BTW you're envited to contribute to upstream WYMeditor.

**Comment by mightyiam** [comment]
@lehni we've just made some [improvements to browser detection](https://github.com/wymeditor/wymeditor/pull/662).
