### ISSUE TITLE
Make jquery dependency optional

### ISSUE THREAD

**Issue by jcbvm** [gabceb/jquery-browser-plugin#54]
I know this sounds a little weird because the name of this project is jquery-browser-plugin, but it doesn't seem to use jquery for anything. Currently I want to use this plugin to detect the browser before the app launches, therefor I need jquery (I use jquery version 2, old IE versions are not supported) which may break on non supported browsers.

**Comment by le717** [comment]
@gabceb Maybe we don't need a separate repo after all...

https://gist.github.com/yckart/5563717#file-jquery-addrule-js-L37-L40

https://gist.github.com/yckart/5563717#comment-829398

And I don't think this would require any AMD/Node.js support changes either.

**Comment by le717** [comment]
@jcbvm I've implemented this at #56, if you'd like to look at it.

**Comment by jcbvm** [comment]
@le717 This looks good to me. I think it's fine to run the code automatically on page load, so just assigning the result to jQBrowser instead of exposing it as a function. But I'm fine with both.

**Comment by le717** [comment]
@jcbvm I'll update it to run on page load (as that matches the jQuery behavior), but I would still like to have a function available if someone wanted to detect a browser by an arbitrary UA. There are probably instances somewhere where this happens, and exposing a function allows that. @gabceb and I will, of course, pound out any details, but I'd like to hear your thoughts on that use case.

**Comment by jcbvm** [comment]
I think one solution would be to keep the jQuery.uaMatch and add the function window.jQBrowser.uaMatch with the same behaviour as jQuery.uaMatch. This way you will have full compatibility with the old version. Or you can move the uaMatch to the returned object (as a function), that way both the jquery and global versions are exactly the same.

**Comment by gabceb** [comment]
Fixed by #56. Thanks @le717

**Comment by le717** [comment]
@jcbvm This is now available in v0.0.8, now available on npm. :)

**Comment by jcbvm** [comment]
Cool, many thanks!
