### ISSUE TITLE
Does this also allow styling through css selectors?

### ISSUE THREAD

**Issue by master412160** [gabceb/jquery-browser-plugin#60]
Does it add css support per browser or device? 

Or is it plainly detection?

I'm a bit new to jquery but would I have to write the css in the script then or assign new classes?

**Comment by gabceb** [comment]
This plugin does only plain js detection. If you want to style elements based on the device you can either add the css classes once you have detected the device you need or what I would do is to add a the device name on the body element and then add css rules that only apply when such class is available.

Example:

```javascript
$( document ).ready(function() {
    if($.browser.ipad) {
        $('body').addClass('ipad');
    }
});
```

```css
body.ipad {
    font-size: 18px;
}
```

Reopen issue if you have more questions!

**Comment by le717** [comment]
I was just about to say the same thing, @gabceb. :P
