### ISSUE TITLE
version bump

### ISSUE THREAD

**Issue by peter-mouland** [gabceb/jquery-browser-plugin#62]
seems like quite a while since git has been tagged with the latest version.
are you able to do a bump so i can remove the git repo address from my bower.json?

**Comment by le717** [comment]
I'm going to try to run over #57 and #58 today then see about a bump. We've got a number of changes to make to detect some new UAs, and I've got an idea I need to post that may help improve the plugin.

**Comment by le717** [comment]
#57 and #58 have been resolved. I can technically make a release but only @gabceb can push to npm...

@gabceb Do you want me to make a new release and you can push it to npm when you get the time?

**Comment by gabceb** [comment]
Yes please. Ill push the new version tonight

**Comment by le717** [comment]
v0.0.8 tagged. You can close this when you push it out or I can catch it later. :)

**Comment by gabceb** [comment]
Done!
