### ISSUE TITLE
Support Microsoft Edge

### ISSUE THREAD

**Issue by le717** [gabceb/jquery-browser-plugin#63]
Win10 comes out July 29, and I'm almost sure the new UA is on MSDN.

**Comment by le717** [comment]
@gabceb How do you think MS Edge should be handled? I would refrain from stuffing it under `browser.msie`. The EdgeHTML engine may be a fork from Trident, but it is so radically changed that grouping it with IE is unfair. How about `browser.msedge` or even (if possible) `browser.edge`?

**Comment by jcbvm** [comment]
Any progress on this?

**Comment by bfeist** [comment]
browser.edge plz

**Comment by le717** [comment]
I'm looking into this as I type this message, seems we already detect it but need a small bit of refactoring to expose it.

@gabceb My question [above](https://github.com/gabceb/jquery-browser-plugin/issues/63#issuecomment-114683610) still stands with an addition: the "name" key. Because the browser name is officially Microsoft Edge, I think all IDs to it should be `msedge`. `msie` happened because of legacy UAs, hence why we use that. With Edge, we could possibly avoid that and simply use `edge` but I am reluctant to because `msedge` would be inline with the official name.

BTW, here is the resulting browser object for MS Edge:
```json
{
    "version": "13.10586",
    "versionNumber": 13,
    "win": true,
    "desktop": true,
    "msedge": true,
    "name": "msedge",
    "platform": "win"
}
```

**Comment by gabceb** [comment]
According to Wikipedia `Microsoft Edge is a web browser developed by Microsoft` so we can assume Microsoft is part of the name hence should be named `msedge`. Google Chrome is actually called `Chrome` as per Google's download page.

**Comment by le717** [comment]
We also have [this post](http://blogs.windows.com/msedgedev/2015/04/29/introducing-microsoft-edge-the-browser-built-for-windows-10/) on the official blog: "We’re excited to share Joe’s announcement that Project Spartan’s official name is **Microsoft Edge**.", so `msedge` it is. I'll finish up my changes and submit a PR ASAP. :)

**Comment by gabceb** [comment]
Do it

![image](https://cloud.githubusercontent.com/assets/470852/11347024/7dd40b28-91d4-11e5-8068-4d70a132826e.png)

**Comment by le717** [comment]
Microsoft Edge is now supported in v0.1.0 under the key `

**Comment by le717** [comment]
Microsoft Edge is now supported in v0.1.0 under the key `browser.msedge`. Enjoy. :)
