### ISSUE TITLE
jQBrowser.mobile returns undefined instead of false

### ISSUE THREAD

**Issue by spectodesign** [gabceb/jquery-browser-plugin#65]
Some of the variables are not initialized to false:

EXISTING:
    if ( browser.android || browser.bb || browser.blackberry || browser.ipad || browser.iphone ||
      browser.ipod || browser.kindle || browser.playbook || browser.silk || browser[ "windows phone" ]) {
      browser.mobile = true;
    } 

checking for jQBrowser.mobile on a desktop browser will return 'undefined' instead of false.

FIX:
    if ( browser.android || browser.bb || browser.blackberry || browser.ipad || browser.iphone ||
      browser.ipod || browser.kindle || browser.playbook || browser.silk || browser[ "windows phone" ]) {
      browser.mobile = true;
    } else {
      browser.mobile = false;
    }

The same problem for browser.desktop, browser.safari, browser.xyz

**Comment by le717** [comment]
I'd be reluctant to change this as it breaks backward-compatibility, but TBH it's not a problem if you just check for falsy values instead of strictly `false`, e.g.,

`if (!jQBrowser.mobile) { }` vs `if (jQBrowser.mobile === false) { }`

I am really not sure here...

**Comment by gabceb** [comment]
+1 to ^^

**Comment by le717** [comment]
@gabceb To be clear, who are you +1'ing, me or the OP? Just want to fully understand the discussion. :)

**Comment by le717** [comment]
Closing with no intention to fix as current behavior is acting as designed. Also, the object you receive describes the browser it detected and any attributes it contains. It is not supposed to list attributes that do not apply to it (like `.webkit` if IE is detected, as IE uses Trident).
