### ISSUE TITLE
Windows Phone not recognized

### ISSUE THREAD

**Issue by MoonYard** [gabceb/jquery-browser-plugin#67]
Name: Windows Phone
Modell: NOKIA Lumia 520
Software: Windows Phone 8.1 Update
(OS Version: 8.10.14219.341)

$.browser {
 "webkit":true,
 "version","537", 
 "versionNumber":537,
 "iphone":true,
 "mobile":true,
 "name":"webkit",
 "platform":"iphone"
}

"Mozilla/5.0 (Mobile; WIndows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 520) like iPhone OS 7_0_3 Mac OS X AppleWebkit/537 (KHTML, like Gecko) Mobile Safari/537"

Thanks (:

**Comment by MoonYard** [comment]
I fix the problem with the following steps:

Fix Browser:
```javascript
/(chrome)[ \/]([\w.]+)/.exec( ua ) ||
// added on line 43
/(iemobile)[\/]([\w.]+)/.exec( ua ) ||
// addedd stop
/(version)(applewebkit)[ \/]([\w.]+).*(safari)[ \/]([\w.]+)/.exec( ua ) ||
```
Fix Browser part 2:
```javascript
// added  to line 104 browser.iemobile
if ( browser.rv || browser.edge || browser.iemobile) {
// added stop
```
Fix Platform:
```javascript
// move from line 58 (after android)
/(windows phone)/.exec( ua ) ||
// to line 54 (after ipod)
```

**Comment by le717** [comment]
Would you like to submit a pull request and add that UA to the test suite so we can be sure all is well,?

**Comment by MoonYard** [comment]
I've done. I hope it's okay.

**Comment by le717** [comment]
Thank you for reporting and fixing this! I have merged your changes into the `master` branch. :smiley:
